INSERT INTO [dbo].[APS_RUNNING_CONFIG]
           ([Num]
           ,[OrgCode]
           ,[CardTypeCode]
           ,[CardTypeName]
           ,[Bin]
           ,[CreditCardType]
           ,[FromNumber]
           ,[ToNumber]
           ,[CurrentNumber]
           ,[UpdateBy]
           ,[CreateDate]
           ,[UpdateDate]
           ,[ACCNO_FROM]
           ,[ACCNO_TO]
           ,[ACCNO_CURRENT]
           ,[FLAG]
           ,[FROM_NUMBER_SUBCARD]
           ,[TO_NUMBER_SUBCARD]
           ,[CURRENT_NUMBER_SUBCARD])
     VALUES
           (11
           ,1
           ,901
           ,'บัตรโชห่วย-ไปรษณีย์ไทย'
           ,3026
           ,1
           ,1
           ,9999999
           ,1
           ,'SYSTEM'
           ,GETDATE()
           ,GETDATE()
           ,1
           ,9999999
           ,1
           ,1
           ,1
           ,9999999
           ,1);
