USE [apsweb1]
GO

/****** Object:  Table [dbo].[APS_WRITE_OFF_MASTER]    Script Date: 10/3/2018 8:03:50 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[APS_WRITE_OFF_TRANSACTION](
	[CID] [varchar](13) NOT NULL,
	[NAME] [varchar](200) NULL,
	[SURNAME] [varchar](200) NULL,
	[EXPORT_DATE] [datetime] NULL,
	[CREATE_DATE] [datetime] NULL,
	[UPDATE_DATE] [datetime] NULL,
 CONSTRAINT [PK_APS_WRITE_OFF_TRANSACTION] PRIMARY KEY CLUSTERED 
(
	[CID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


