select GEN_CLK_FILE_DATE,APPL_STATUS,REGISTER_TYPE,BILLING_CUST_TYPE,* 
from APS_APPL_MASTER 
where 
APPL_STATUS IN(13,14,15)
--and REGISTER_TYPE=3
and GEN_CLK_FILE_DATE is null;








--update APS_APPL_MASTER set BILLING_CUST_TYPE = 'ST' where APPL_ID  in('S610000278');

select * from [dbo].[APS_APPL_PROFILE] where APPL_ID in('S610000276');

select CardTypeCode,
'' as OLD_ACC,	
ACCNO_CURRENT as CURRENT_ACC,	
'' as OLD_MAINCARD,	
CurrentNumber as CURRENT_MAINCARD,
'' as OLD_SUB,
CURRENT_NUMBER_SUBCARD as CURRENT_SUB
from APS_RUNNING_CONFIG order by CardTypeCode;


--select * from [dbo].[APS_CARD_NO_RESERVE];
--update APS_APPL_MASTER set GEN_CLK_FILE_DATE = NULL where APPL_ID  in('C610000347');
--
update APS_APPL_MASTER set GEN_CLK_FILE_DATE = NULL where APPL_ID  in('S610000236');


select * from [dbo].[APS_APPL_PROFILE] 
where APPL_ID in(select APPL_ID from APS_APPL_MASTER where APPL_STATUS=15 and REGISTER_TYPE=3) and BORROWER_TYPE <> 'P';




select 
APS_APPL_MASTER.PRODUCT_TYPE,
APS_APPL_MASTER.APPL_ID,
APS_APPL_MASTER.REGISTER_TYPE,
APS_APPL_APPROVAL_MEMO.CA2_RCMND_CARD_TYPE_CODE,
APS_APPL_APPROVAL_MEMO.CA2_APPL_RESULT_CODE,
APS_APPL_APPROVAL_MEMO.SUP1_CA2_APPL_RESULT_CODE,
APS_APPL_APPROVAL_MEMO.SUP2_CA2_APPL_RESULT_CODE,
APS_APPL_APPROVAL_MEMO.SUP3_CA2_APPL_RESULT_CODE,
APS_APPL_APPROVAL_MEMO.SUP4_CA2_APPL_RESULT_CODE
from APS_APPL_APPROVAL_MEMO
left join APS_APPL_MASTER on APS_APPL_MASTER.APPL_ID = APS_APPL_APPROVAL_MEMO.APPL_ID
where 
--CA2_RCMND_CARD_TYPE_CODE='821' and
APS_APPL_MASTER.APPL_ID in(
'S610000236');

-- xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx


select 
CA2_RCMND_CARD_TYPE_CODE,
SUM(case 
when ISNULL(CA2_APPL_RESULT_CODE,0) = 5 then 1
when ISNULL(CA2_APPL_RESULT_CODE,0) = 2 then 1
else 0 end) CA2_APPROVED,
SUM(case 
when ISNULL(SUP1_CA2_APPL_RESULT_CODE,0) = 5 then 1
when ISNULL(SUP1_CA2_APPL_RESULT_CODE,0) = 2 then 1
else 0 end) SUP1,
SUM(case 
when ISNULL(SUP2_CA2_APPL_RESULT_CODE,0) = 5 then 1
when ISNULL(SUP2_CA2_APPL_RESULT_CODE,0) = 2 then 1
else 0 end) SUP2,
SUM(case 
when ISNULL(SUP3_CA2_APPL_RESULT_CODE,0) = 5 then 1
when ISNULL(SUP3_CA2_APPL_RESULT_CODE,0) = 2 then 1
else 0 end) SUP3,
SUM(case 
when ISNULL(SUP4_CA2_APPL_RESULT_CODE,0) = 5 then 1
when ISNULL(SUP4_CA2_APPL_RESULT_CODE,0) = 2 then 1
else 0 end) SUP4
from APS_APPL_APPROVAL_MEMO where APPL_ID in(
'S610000236'
--'C610000392',
--'C610000397',
--'C610000398',
--'C610000399',
--'C610000400',
--'C610000401',
--'C610000402',
--'C610000403',
--'R610000075',
--'R610000076',
--'S610000270',
--'S610000271'
)
group by CA2_RCMND_CARD_TYPE_CODE;

-- ===
select INC_AMT,* from VW_APPROVAL_MEMO where APPL_ID ='S610000236';



select SUBDISTRICT_CODE,* from APS_APP_DET_WORKING where APPL_ID='C610000319' and cid='1619900008424';




SELECT * FROM APS_APP_DET_WORKING;
