SELECT Num,Bin,CreditCardType,FromNumber,ToNumber,CurrentNumber,
ACCNO_FROM,ACCNO_TO,ACCNO_CURRENT,
FROM_NUMBER_SUBCARD,TO_NUMBER_SUBCARD,CURRENT_NUMBER_SUBCARD,CardTypeCode 
FROM APS_RUNNING_CONFIG WHERE APS_RUNNING_CONFIG.CardTypeCode = '901' AND FLAG = 1;




