WITH APP_MASTER AS ( 
 SELECT * FROM [dbo].[APS_APPL_MASTER] 
) 
SELECT * FROM APP_MASTER;


SELECT 
M.APPL_ID,
P.FIRST_NAME_TH,
P.CID,H.STATUS,
S.APPL_STATUS_NAME, 
M.CREATE_DATE AS REGISTER_DATE,
H.UPDATE_DATE AS RESOLVE_DATE,
-- STATUS=4 DIFFDAY(REGISTER_DATE,RESOLVE_DATE)
-- RESOLVE DATE ของ 9-4
--
--
-- TOTAL GSB count จาก 13,14,15,16,17,23 
-- TOTAL APP TAT 
H.USER_NAME AS CA1, -- มาจาก status 9,
H.USER_NAME AS CA2 -- มาจาก status 10,
FROM [dbo].[APS_APPL_MASTER] M
LEFT JOIN APS_APPL_PROFILE P ON M.APPL_ID = P.APPL_ID
LEFT JOIN APS_APP_INQUIRY_HISTORY H ON M.APPL_ID = H.APPL_ID
LEFT JOIN APS_APPL_STATUS S ON S.APPL_STATUS = H.STATUS
WHERE M.APPL_ID ='C610000165' 
AND P.CID='1209700326680'
--AND H.STATUS IN (13,14,15,16,17,23)
ORDER BY S.APPL_STATUS_NAME
