WITH 
hIncompleteDoc AS( 
 SELECT APPL_ID appid,abs(DATEDIFF(day,MAX(UPDATE_DATE),MIN(UPDATE_DATE))) daydiff
 FROM APS_APP_INQUIRY_HISTORY WHERE STATUS IN (12)
 GROUP BY APPL_ID 
),
hRWCA1 AS( 
 SELECT APPL_ID appid,abs(DATEDIFF(day,MAX(UPDATE_DATE),MIN(UPDATE_DATE)))+1 daydiff,MAX(UPDATE_DATE) update_date 
 FROM APS_APP_INQUIRY_HISTORY WHERE STATUS IN (19,13,14,23,15,16,17,4)
 GROUP BY APPL_ID 
),
hWCA1ICA1 AS( 
 SELECT APPL_ID appid,abs(DATEDIFF(day,MAX(UPDATE_DATE),MIN(UPDATE_DATE)))+1 daydiff,MAX(UPDATE_DATE) update_date 
 FROM APS_APP_INQUIRY_HISTORY WHERE STATUS IN (4,13,14,23,15,16,17,9)
 GROUP BY APPL_ID 
),
hICACCA1 AS( 
 SELECT APPL_ID appid,abs(DATEDIFF(day,MAX(UPDATE_DATE),MIN(UPDATE_DATE)))+1 daydiff,MAX(UPDATE_DATE) update_date 
 FROM APS_APP_INQUIRY_HISTORY WHERE STATUS IN (9,13,14,23,15,16,17,5)
 GROUP BY APPL_ID 
),
hWCA2ICA2 AS( 
 SELECT APPL_ID appid,abs(DATEDIFF(day,MAX(UPDATE_DATE),MIN(UPDATE_DATE)))+1 daydiff,MAX(UPDATE_DATE) update_date 
 FROM APS_APP_INQUIRY_HISTORY WHERE STATUS IN (5,13,14,23,15,16,17,10)
 GROUP BY APPL_ID 
),
hICA2R AS( 
 SELECT APPL_ID appid,abs(DATEDIFF(day,MAX(UPDATE_DATE),MIN(UPDATE_DATE)))+1 daydiff,MAX(UPDATE_DATE) update_date 
 FROM APS_APP_INQUIRY_HISTORY WHERE STATUS IN (10,13,14,23,15,16,17)
 GROUP BY APPL_ID 
),
hICA1R AS( 
 SELECT APPL_ID appid,abs(DATEDIFF(day,MAX(UPDATE_DATE),MIN(UPDATE_DATE)))+1 daydiff,MAX(UPDATE_DATE) update_date 
 FROM APS_APP_INQUIRY_HISTORY WHERE STATUS IN (9,13,14,23,15,16,17)
 GROUP BY APPL_ID 
)
SELECT 
M.APPL_ID,
CONCAT(P.FIRST_NAME_TH,'  ',P.LAST_NAME_TH) AS FIRST_NAME_TH,
P.CID,
S.APPL_STATUS_NAME, 
M.CREATE_DATE AS REGISTER_DATE,
IH1.UPDATE_DATE AS RESOLVE_DATE,
(hRWCA1.daydiff-hIncompleteDoc.daydiff) AS R_WCA1,
(hWCA1ICA1.daydiff-hIncompleteDoc.daydiff) AS WCA1_ICA1,
(hICACCA1.daydiff-hIncompleteDoc.daydiff) AS ICA_CCA1,
(hWCA2ICA2.daydiff-hIncompleteDoc.daydiff) AS WCA2_ICA2,
(hICA2R.daydiff-hIncompleteDoc.daydiff) AS ICA2_R,
(hICA1R.daydiff-hIncompleteDoc.daydiff) AS ICA1_R,
abs(DATEDIFF(day,M.CREATE_DATE,IH1.UPDATE_DATE))+1  AS TOTAL_GSB_TAT,
abs(DATEDIFF(day,M.CREATE_DATE,IH1.UPDATE_DATE))+1 AS TOTAL_APPL_TAT,
IH1.USER_NAME AS CA1, -- �Ҩҡ status 9,
IH1.USER_NAME AS CA2 -- �Ҩҡ status 10,
FROM [dbo].[APS_APPL_MASTER] M
LEFT JOIN APS_APPL_PROFILE P ON M.APPL_ID = P.APPL_ID
LEFT JOIN APS_APPL_STATUS S ON S.APPL_STATUS = M.APPL_STATUS
JOIN hIncompleteDoc ON hIncompleteDoc.appid = M.APPL_ID
LEFT JOIN APS_APP_INQUIRY_HISTORY IH1 ON M.APPL_ID = IH1.APPL_ID and IH1.STATUS IN (19,13,14,23,15,16,17,4) --
JOIN hRWCA1 ON hRWCA1.appid = M.APPL_ID AND hRWCA1.update_date = IH1.UPDATE_DATE
LEFT JOIN APS_APP_INQUIRY_HISTORY IH2 ON M.APPL_ID = IH2.APPL_ID and IH2.STATUS IN (4,13,14,23,15,16,17,9) --
JOIN hWCA1ICA1 ON hWCA1ICA1.appid = M.APPL_ID AND hWCA1ICA1.update_date = IH2.UPDATE_DATE
LEFT JOIN APS_APP_INQUIRY_HISTORY IH3 ON M.APPL_ID = IH3.APPL_ID and IH3.STATUS IN (9,13,14,23,15,16,17,5) --
JOIN hICACCA1 ON hICACCA1.appid = M.APPL_ID AND hICACCA1.update_date = IH3.UPDATE_DATE
LEFT JOIN APS_APP_INQUIRY_HISTORY IH4 ON M.APPL_ID = IH4.APPL_ID and IH4.STATUS IN (5,13,14,23,15,16,17,10) --XXXXX
JOIN hWCA2ICA2 ON hWCA2ICA2.appid = M.APPL_ID AND hWCA2ICA2.update_date = IH4.UPDATE_DATE
LEFT JOIN APS_APP_INQUIRY_HISTORY IH5 ON M.APPL_ID = IH5.APPL_ID and IH5.STATUS IN (10,13,14,23,15,16,17) --
JOIN hICA2R ON hICA2R.appid = M.APPL_ID AND hICA2R.update_date = IH5.UPDATE_DATE
LEFT JOIN APS_APP_INQUIRY_HISTORY IH6 ON M.APPL_ID = IH6.APPL_ID and IH6.STATUS IN (9,13,14,23,15,16,17) --
JOIN hICA1R ON hICA1R.appid = M.APPL_ID AND hICA1R.update_date = IH6.UPDATE_DATE
WHERE P.BORROWER_TYPE='P'
AND M.APPL_ID ='C610000161';


--SELECT SUBMIT_PROCESS,*
--  FROM [apsweb1].[dbo].[APS_APPL_MASTER] where SUBMIT_PROCESS=4;

--  select *  FROM APS_APP_INQUIRY_HISTORY where APPL_ID ='C610000161';

 --SELECT *--APPL_ID appid,abs(DATEDIFF(day,MAX(UPDATE_DATE),MIN(UPDATE_DATE))) daydiff
 --FROM APS_APP_INQUIRY_HISTORY WHERE STATUS IN (12) AND APPL_ID='C610000161'
 --GROUP BY APPL_ID 