-- 1)
select APPL_ID,BILLING_CUST_TYPE,PRODUCT_TYPE,* from APS_APPL_MASTER where APPL_ID in ('C620068243');
-- 2)
select APPL_ID,BORROWER_TYPE,* from APS_APPL_PROFILE where APPL_ID in ('C620068243');
-- 3)

select CA2_RCMND_CARD_TYPE_CODE,CA2_CARD_LIMIT_AMT,* from APS_APPL_APPROVAL_MEMO where APPL_ID in ('C610278189','C610278212');

select * from APS_BILLING_CYCLE_CONFIG 
where BILLING_CUST_TYPE='' --> 1)
and PRODUCT_TYPE_CODE='' --> 1)
and BORROWER_TYPE='' --> 2)
and CARD_TYPE_CODE='' --> 3)



select * from APS_APPL_APPROVAL_MEMO where APPL_ID='S620000010';

select CA2_CARD_LIMIT_AMT,* from APS_APPL_MASTER;