--/
-- Batch submitted through debugger: sql_createstore.sql|8683|0|\\Mac\Home\Desktop\sql_createstore.sql
/*MONCHIAN T.*/
    alter PROCEDURE sp_TxnReqLG_Execute 
    (
            @ReqID nvarchar(30),
            @ReqDate date = NULL,
            @OldLGNo nvarchar(20) = NULL,
            @ObjectiveID nvarchar(2) = NULL,
            @BEID nvarchar(38) = NULL,
            @AuthorityName nvarchar(100) = NULL,
            @LGAmt decimal = NULL,
            @BenefitaryCode nvarchar(5) = NULL,
            @BeneDetail nvarchar(255) = NULL,
            @ScheduleFlag varchar(1) = NULL,
            @StartDate date = NULL,
            @EndDate date = NULL,
            @Detail nvarchar(max) = NULL,
            @Remark nvarchar(max) = NULL,
            @AttachedFileFlag varchar(1) = NULL,
            @AuthorSign1 nvarchar(100) = NULL,
            @AuthorSign2 nvarchar(100) = NULL,
            @AuthorSignPosition1 nvarchar(100) = NULL,
            @AuthorSignPosition2 nvarchar(100) = NULL,
            @ReqStatus varchar(1) = NULL,
            @UserCode nvarchar(6) = NULL,
            @DateEntry datetime = NULL,
            @OCCode nvarchar(4) = NULL,
            @AccountNo varchar(50) = NULL,
            @PartyID nvarchar(40) = NULL,
            @PartyName nvarchar(max) = NULL,
            @BirthDay date = NULL,
            @Nationality nvarchar(255) = NULL,
            @Citizenship nvarchar(255) = NULL,
            @DealNo decimal = NULL,
            @PartyType nvarchar(3) = NULL,
            @Married varchar(1) = NULL,
            @EmailAddress nvarchar(50) = NULL,
            @PhoneNo nvarchar(50) = NULL,
            @AddressNo nvarchar(25) = NULL,
            @Moo nvarchar(10) = NULL,
            @Soi nvarchar(40) = NULL,
            @Street nvarchar(50) = NULL,
            @Trok nvarchar(20) = NULL,
            @District nvarchar(40) = NULL,
            @Amphur nvarchar(40) = NULL,
            @ProvinceID nvarchar(50) = NULL,
			@PartyAge nvarchar(50) = NULL,
			@AccountType nvarchar(30) = NULL,
			@AccountName nvarchar(255) = NULL,
			@AccountBranch nvarchar(255) = NULL,
			@EMobileNo nvarchar(10) = NULL,
			@EEmailAddress nvarchar(100) = NULL,
			@UserBranch nvarchar(6) = NULL,
            @FLAG CHAR(1)
    )
    AS
    IF(@FLAG = 'I') --INSERT FUNCTION
    BEGIN
        INSERT INTO [TxnReqLG]
            (
            [ReqID],
            [ReqDate],
            [OldLGNo],
            [ObjectiveID],
            [BEID],
            [AuthorityName],
            [LGAmt],
            [BenefitaryCode],
            [BeneDetail],
            [ScheduleFlag],
            [StartDate],
            [EndDate],
            [Detail],
            [Remark],
            [AttachedFileFlag],
            [AuthorSign1],
            [AuthorSign2],
            [AuthorSignPosition1],
            [AuthorSignPosition2],
            [ReqStatus],
            [UserCode],
            [DateEntry],
            [OCCode],
            [AccountNo],
            [PartyID],
            [PartyName],
            [BirthDay],
            [Nationality],
            [Citizenship],
            [DealNo],
            [PartyType],
            [Married],
            [EmailAddress],
            [PhoneNo],
            [AddressNo],
            [Moo],
            [Soi],
            [Street],
            [Trok],
            [District],
            [Amphur],
            [ProvinceID],
			[PartyAge],
			[AccountType],
			[AccountName],
			[AccountBranch],
			[EMobileNo],
			[EEmailAddress],[UserBranch]
			)
        VALUES
            (
            @ReqID,
            @ReqDate,
            @OldLGNo,
            @ObjectiveID,
            @BEID,
            @AuthorityName,
            @LGAmt,
            @BenefitaryCode,
            @BeneDetail,
            @ScheduleFlag,
            @StartDate,
            @EndDate,
            @Detail,
            @Remark,
            @AttachedFileFlag,
            @AuthorSign1,
            @AuthorSign2,
            @AuthorSignPosition1,
            @AuthorSignPosition2,
            @ReqStatus,
            @UserCode,
            @DateEntry,
            @OCCode,
            @AccountNo,
            @PartyID,
            @PartyName,
            @BirthDay,
            @Nationality,
            @Citizenship,
            @DealNo,
            @PartyType,
            @Married,
            @EmailAddress,
            @PhoneNo,
            @AddressNo,
            @Moo,
            @Soi,
            @Street,
            @Trok,
            @District,
            @Amphur,
            @ProvinceID,
			@PartyAge,
			@AccountType,
			@AccountName,
			@AccountBranch,
			@EMobileNo,
			@EEmailAddress,@UserBranch
			)
    END
    ELSE IF(@FLAG = 'U') --UPDATE FUNCTION
    BEGIN
        UPDATE [TxnReqLG] SET 
            [ReqDate] = @ReqDate,
            [OldLGNo] = @OldLGNo,
            [ObjectiveID] = @ObjectiveID,
            [BEID] = @BEID,
            [AuthorityName] = @AuthorityName,
            [LGAmt] = @LGAmt,
            [BenefitaryCode] = @BenefitaryCode,
            [BeneDetail] = @BeneDetail,
            [ScheduleFlag] = @ScheduleFlag,
            [StartDate] = @StartDate,
            [EndDate] = @EndDate,
            [Detail] = @Detail,
            [Remark] = @Remark,
            [AttachedFileFlag] = @AttachedFileFlag,
            [AuthorSign1] = @AuthorSign1,
            [AuthorSign2] = @AuthorSign2,
            [AuthorSignPosition1] = @AuthorSignPosition1,
            [AuthorSignPosition2] = @AuthorSignPosition2,
            [ReqStatus] = @ReqStatus,
            [UserCode] = @UserCode,
            [DateEntry] = @DateEntry,
            [OCCode] = @OCCode,
            [AccountNo] = @AccountNo,
            [PartyID] = @PartyID,
            [PartyName] = @PartyName,
            [BirthDay] = @BirthDay,
            [Nationality] = @Nationality,
            [Citizenship] = @Citizenship,
            [DealNo] = @DealNo,
            [PartyType] = @PartyType,
            [Married] = @Married,
            [EmailAddress] = @EmailAddress,
            [PhoneNo] = @PhoneNo,
            [AddressNo] = @AddressNo,
            [Moo] = @Moo,
            [Soi] = @Soi,
            [Street] = @Street,
            [Trok] = @Trok,
            [District] = @District,
            [Amphur] = @Amphur,
            [ProvinceID] = @ProvinceID,
			[PartyAge]=@PartyAge,
			[AccountType]=@AccountType,
			[AccountName]=@AccountName,
			[AccountBranch]=@AccountBranch,
			[EMobileNo]=@EMobileNo,
			[EEmailAddress]=@EEmailAddress,
			[UserBranch]=@UserBranch
        WHERE 
            ReqID = @ReqID
        SELECT @ReqID AS ReqID
    END



/
